stages:
  - build
  - deploy

#include:
#  - template: Managed-Cluster-Applications.gitlab-ci.yml

default:
  #  image: alvrme/alpine-android:android-29-jdk11
  tags:
    - macos
  before_script:
    - git submodule update --init --checkout

variables:
  ANDROID_SDK_ROOT: /Users/builder/Library/Android/sdk
  SIGNING_KEY: /builds/breadwallet/brd-mobile/brd-android/FakeSigningKey
  SIGNING_PASSWORD: qwerty
  SIGNING_ALIAS: key0
  SIGNING_ALIAS_PASSWORD: qwerty
  ORG_GRADLE_DAEMON: "false"
  ORG_GRADLE_DEPENDENCY_VERIFICATION: "off"
  ORG_GRADLE_CONSOLE: plain
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone

cache:
  key: ${CI_PROJECT_ID}-3
  paths:
    - ~/.gradle/
    - /root/.gradle/

build-cosmos:
  stage: build
  script:
    - ./gradlew allTest --no-daemon
  only:
    refs:
      - main
      - develop
      - merge_requests
    changes:
      - buildSrc/**/Libs.kt
      - cosmos-*/**/*
      - .gitlab-ci.yml
  artifacts:
    when: on_failure
    paths:
      - ./**/build/reports/tests

build-android:
  stage: build
  script:
    - ./gradlew :brd-android:app:build -xlint -xdetekt --no-daemon
  only:
    refs:
      - main
      - develop
      - merge_requests
    changes:
      - buildSrc/**/Libs.kt
      - buildSrc/**/BrdRelease.kt
      - brd-android/**/*
      - cosmos-*/**/*
      - .gitlab-ci.yml
  artifacts:
    when: always
    paths:
      - brd-android/app/build/outputs/apk/brd/debug/
      - brd-android/app/build/outputs/apk/brd/release/
      - brd-android/app/build/outputs/apk/brdTestnet/debug/
      - brd-android/app/build/outputs/apk/brdTestnet/release/
      - ./**/build/reports/**/*
    reports:
      junit: ./brd-android/**/build/test-results/**/TEST-*.xml

build-ios:
  stage: build
  only:
    refs:
      - main
      - develop
      - merge_requests
    changes:
      - buildSrc/**/Libs.kt
      - brd-ios/**/*
      - cosmos-*/**/*
      - .gitlab-ci.yml
  script:
    - ./gradlew :cosmos-bundled:createXCFramework
    - xcodebuild clean -workspace brd-ios/breadwallet.xcworkspace -scheme breadwallet | xcpretty
    - xcodebuild test -workspace brd-ios/breadwallet.xcworkspace -scheme breadwallet -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' | xcpretty -s
  tags:
    - macos

deploy-appetize:
  stage: deploy
  needs: [ "build-android" ]
  script:
    - ./gradlew appetizeUpload
  only:
    refs:
      - merge_requests
    changes:
      - buildSrc/**/Libs.kt
      - brd-android/**/*
      - cosmos-*/**/*
      - .gitlab-ci.yml
  environment:
    name: Review $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    url: $NATIVE_REVIEW_URL?versionName=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    on_stop: stop-review

stop-review:
  stage: deploy
  needs: [ "build-android" ]
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - cd $CI_PROJECT_DIR; ./gradlew appetizeRemove -Pmerge=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  when: manual
  only:
    refs:
      - merge_requests
    changes:
      - buildSrc/**/Libs.kt
      - brd-android/**/*
      - cosmos-*/**/*
      - .gitlab-ci.yml
  environment:
    name: Review $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    action: stop

deploy-firebase:
  stage: deploy
  variables:
    ORG_GRADLE_DEPENDENCY_VERIFICATION: "off"
  script:
    - ./gradlew :brd-android:app:assemble
    - ./gradlew :brd-android:app:appDistributionUploadBrdRelease
    - ./gradlew :brd-android:app:uploadCrashlyticsSymbolFileBrdRelease
    - ./gradlew :brd-android:app:appDistributionUploadBrdTestnetRelease
    - ./gradlew :brd-android:app:uploadCrashlyticsSymbolFileBrdTestnetRelease
    - ./gradlew :brd-android:app:appDistributionUploadBrdDebug
    - ./gradlew :brd-android:app:uploadCrashlyticsSymbolFileBrdDebug
    - ./gradlew :brd-android:app:appDistributionUploadBrdTestnetDebug
    - ./gradlew :brd-android:app:uploadCrashlyticsSymbolFileBrdTestnetDebug
    - ./gradlew postToSlack
  rules:
    - if: '$CI_COMMIT_TAG != null && $CI_COMMIT_TAG =~ /^android/'
  artifacts:
    paths:
      - brd-android/app/build/outputs/apk/brd/debug/
      - brd-android/app/build/outputs/apk/brd/release/
      - brd-android/app/build/outputs/apk/brdTestnet/debug/
      - brd-android/app/build/outputs/apk/brdTestnet/release/
